baseurl = "http://flofriday.github.io"
title = "flofriday"
#theme = "hugo-coder"
theme= "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

paginate = 20

#pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  ShowReadingTime = true

[params.homeInfoParams]
  Title = "flofriday"
  Content ="Welcome to my blog."

# Social links
[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/flofriday/"
[[params.socialIcons]]
  name = "Gitlab"
  url = "https://gitlab.com/flofriday/"
#[[params.social]]
#  name = "Twitter"
#  icon = "fa fa-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"